### ISSUE TITLE
Outdated Lands API

### ISSUE THREAD

**Issue by patrikkoudelka** [InsightsPlugin/LandsAddon#1]
Hello, seems like they changed something in API? Can you check it please?

[13:06:14 ERROR]: Could not pass event BlockPlaceEvent to Insights v6.15.0
java.lang.NoSuchMethodError: 'org.bukkit.World me.angeschossen.lands.api.land.ChunkCoordinate.getWorld()'
        at dev.frankheijden.insights.addons.lands.LandsAddon$LandsRegion.toChunkParts(LandsAddon.java:106) ~[?:?]
        at dev.frankheijden.insights.api.listeners.InsightsListener.scanRegion(InsightsListener.java:358) ~[Insights-6.15.0.jar:?]
        at dev.frankheijden.insights.api.listeners.InsightsListener.handleAddonAddition(InsightsListener.java:264) ~[Insights-6.15.0.jar:?]
        at dev.frankheijden.insights.api.listeners.InsightsListener.handleAddition(InsightsListener.java:148) ~[Insights-6.15.0.jar:?]
        at dev.frankheijden.insights.listeners.BlockListener.onBlockPlace(BlockListener.java:77) ~[Insights-6.15.0.jar:?]

**Comment by Angeschossen** [comment]
Opened a PR with a fix: https://github.com/InsightsPlugin/LandsAddon/pull/3
